import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { db } from "@/lib/db";
import {
  users,
  homes,
  homeMembers,
  homeSystems,
  appliances,
  taskInstances,
  householdHealthFlags,
} from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { getApplicableTemplates, getNextDueDate, adjustFrequencyForHealth } from "@/lib/tasks/scheduling";
import type { HealthFlags } from "@/lib/tasks/scheduling";
import type { HomeType, SystemType, ApplianceCategory } from "@/lib/tasks/templates";
import { onboardingSchema } from "@/lib/api/schemas";
import { checkCsrf } from "@/lib/api/handler";
import { rateLimit, RATE_LIMITS } from "@/lib/api/rate-limit";

export async function POST(request: Request) {
  try {
    // CSRF protection
    if (!checkCsrf(request)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const supabase = await createClient();
    const {
      data: { user: authUser },
    } = await supabase.auth.getUser();

    if (!authUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Rate limit onboarding (sensitive — creates many records)
    const rl = rateLimit(`${authUser.id}:onboarding`, RATE_LIMITS.sensitive);
    if (!rl.allowed) {
      return NextResponse.json(
        { error: "Too many requests. Please try again later." },
        { status: 429 }
      );
    }

    // Validate input
    const raw = await request.json();
    const body = onboardingSchema.parse(raw);

    // Upsert our app user record (may not exist yet during first onboarding)
    let [appUser] = await db
      .select()
      .from(users)
      .where(eq(users.authId, authUser.id));

    if (!appUser) {
      [appUser] = await db
        .insert(users)
        .values({
          authId: authUser.id,
          email: authUser.email!,
          name:
            authUser.user_metadata?.full_name ??
            authUser.email!.split("@")[0],
          avatarUrl: authUser.user_metadata?.avatar_url ?? null,
        })
        .returning();
    }

    // Guard against double-submission: if user already has a home, return it
    const [existingMembership] = await db
      .select({ homeId: homeMembers.homeId })
      .from(homeMembers)
      .where(eq(homeMembers.userId, appUser.id))
      .limit(1);

    if (existingMembership) {
      return NextResponse.json({
        success: true,
        homeId: existingMembership.homeId,
        tasksCreated: 0,
        tasksFromSetup: 0,
        tasksAutoGenerated: 0,
        alreadyOnboarded: true,
      });
    }

    // Create home
    const [home] = await db
      .insert(homes)
      .values({
        userId: appUser.id,
        name: body.home.name,
        type: body.home.type as HomeType,
        yearBuilt: body.home.yearBuilt,
        squareFootage: body.home.sqft,
        zipCode: body.home.zip,
        state: body.home.state,
        climateZone: body.home.climateZone,

      })
      .returning();

    // Create owner membership
    await db.insert(homeMembers).values({
      homeId: home.id,
      userId: appUser.id,
      role: "owner",
    });

    // Store household health flags if provided
    if (body.householdHealth) {
      await db.insert(householdHealthFlags).values({
        homeId: home.id,
        ...body.householdHealth,
      });
    }

    // Create home systems
    if (body.systems.length > 0) {
      await db.insert(homeSystems).values(
        body.systems.map((s) => ({
          homeId: home.id,
          systemType: s.key as SystemType,
          subtype: s.subtype,
        }))
      );
    }

    // Create appliances
    if (body.appliances.length > 0) {
      await db.insert(appliances).values(
        body.appliances.map((category) => ({
          homeId: home.id,
          name: category
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          category: category as ApplianceCategory,
        }))
      );
    }

    // Get all applicable templates for this home's configuration
    const healthFlags: HealthFlags = body.householdHealth ?? {};
    const applicableTemplates = getApplicableTemplates(
      {
        type: body.home.type as HomeType,
        systems: body.systems.map((s) => s.key as SystemType),
        appliances: body.appliances as ApplianceCategory[],
      },
      healthFlags
    );

    const templateMap = new Map(applicableTemplates.map((t) => [t.id, t]));

    // Track which template IDs the user explicitly addressed
    const userHandledTemplateIds = new Set(
      body.taskSetups.map((s) => s.templateId)
    );

    // Track which template IDs the user explicitly skipped
    const userSkippedTemplateIds = new Set(
      body.taskSetups.filter((s) => s.state === "skip").map((s) => s.templateId)
    );

    // ── 1. Create task instances from user's explicit selections (track/done) ──
    const activeSetups = body.taskSetups.filter((s) => s.state !== "skip");

    const userTaskValues = activeSetups
      .filter((setup) => templateMap.has(setup.templateId))
      .map((setup) => {
        const template = templateMap.get(setup.templateId)!;

        const adjustedFrequency = adjustFrequencyForHealth(
          template.frequencyValue,
          template.healthMultipliers,
          healthFlags
        );

        let lastCompletedDate: Date | null = null;
        if (setup.state === "done") {
          lastCompletedDate = new Date(
            setup.doneYear,
            setup.doneMonth - 1,
            15
          );
        }

        const nextDueDate = getNextDueDate(
          adjustedFrequency,
          template.frequencyUnit,
          lastCompletedDate ?? undefined
        );

        return {
          homeId: home.id,
          name: template.name,
          description: template.description,
          category: template.category,
          priority: template.priority,
          frequencyUnit: template.frequencyUnit,
          frequencyValue: adjustedFrequency,
          nextDueDate: nextDueDate.toISOString().split("T")[0],
          lastCompletedDate: lastCompletedDate
            ? lastCompletedDate.toISOString().split("T")[0]
            : null,
          isActive: true,
          isCustom: false,
          notificationDaysBefore: 3,
          tips: template.tips,
          whyItMatters: template.whyItMatters,
          subgroup: template.subgroup,
        };
      });

    // ── 2. Auto-create tasks for applicable templates the user didn't address ──
    const autoTaskValues = applicableTemplates
      .filter(
        (template) =>
          !userHandledTemplateIds.has(template.id) &&
          !userSkippedTemplateIds.has(template.id)
      )
      .map((template) => {
        const adjustedFrequency = adjustFrequencyForHealth(
          template.frequencyValue,
          template.healthMultipliers,
          healthFlags
        );

        const nextDueDate = getNextDueDate(
          adjustedFrequency,
          template.frequencyUnit
          // no lastCompleted — uses today as base
        );

        return {
          homeId: home.id,
          name: template.name,
          description: template.description,
          category: template.category,
          priority: template.priority,
          frequencyUnit: template.frequencyUnit,
          frequencyValue: adjustedFrequency,
          nextDueDate: nextDueDate.toISOString().split("T")[0],
          lastCompletedDate: null,
          isActive: true,
          isCustom: false,
          notificationDaysBefore: 3,
          tips: template.tips,
          whyItMatters: template.whyItMatters,
          subgroup: template.subgroup,
        };
      });

    // ── 3. Insert all tasks in one batch ──
    const allTaskValues = [...userTaskValues, ...autoTaskValues];

    if (allTaskValues.length > 0) {
      await db.insert(taskInstances).values(allTaskValues);
    }

    return NextResponse.json({
      success: true,
      homeId: home.id,
      tasksCreated: allTaskValues.length,
      tasksFromSetup: userTaskValues.length,
      tasksAutoGenerated: autoTaskValues.length,
    });
  } catch (error) {
    if (
      error instanceof Error &&
      error.name === "ZodError" &&
      "issues" in error
    ) {
      const issues = (error as { issues: Array<{ path: (string | number)[]; message: string }> }).issues;
      return NextResponse.json(
        {
          error: "Validation error",
          details: issues.map((e) => ({
            path: e.path.join("."),
            message: e.message,
          })),
        },
        { status: 400 }
      );
    }

    console.error("[Onboarding Error]", error);
    return NextResponse.json(
      { error: "An unexpected error occurred" },
      { status: 500 }
    );
  }
}
