// ═══════════════════════════════════════════════════════════════════════════
// HoneyDoIQ — Master Task Template Universe
// The core knowledge base of home maintenance tasks.
// ═══════════════════════════════════════════════════════════════════════════

export type TaskCategory =
  | "hvac" | "plumbing" | "electrical" | "safety"
  | "roof_gutters" | "exterior" | "windows_doors" | "appliance"
  | "lawn_landscape" | "pest_control" | "garage" | "pool"
  | "cleaning" | "seasonal";

export type TaskPriority = "safety" | "prevent_damage" | "efficiency" | "cosmetic";

export type HomeType =
  | "single_family" | "townhouse" | "condo"
  | "apartment" | "multi_family" | "mobile_home";

export type ApplianceCategory =
  | "refrigerator" | "dishwasher" | "washing_machine" | "dryer"
  | "oven_range" | "microwave" | "garbage_disposal" | "water_heater"
  | "furnace" | "ac_unit" | "water_softener" | "water_filter"
  | "humidifier" | "dehumidifier" | "garage_door" | "pool_pump"
  | "hot_tub" | "sump_pump" | "generator" | "other";

export type SystemType =
  | "hvac" | "plumbing" | "electrical" | "roofing"
  | "foundation" | "water_source" | "sewage" | "irrigation"
  | "pool" | "security";

export type FrequencyUnit = "days" | "weeks" | "months" | "years" | "one_time";

export type DiyDifficulty = "easy" | "moderate" | "hard" | "professional";

export type HealthCategory =
  | "clean_air"
  | "clean_water"
  | "mold_prevention"
  | "fire_safety"
  | "pest_free"
  | "injury_prevention";

export interface TaskTemplate {
  id: string;
  name: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  frequencyValue: number;
  frequencyUnit: FrequencyUnit;
  estimatedMinutes: number | null;
  estimatedCostLow: number | null;
  estimatedCostHigh: number | null;
  diyDifficulty: DiyDifficulty;
  applicableHomeTypes: HomeType[];
  applicableSystems: SystemType[];
  applicableApplianceCategories: ApplianceCategory[];
  seasonalMonths: number[];
  healthCategories: HealthCategory[];
  tips: string | null;
  whyItMatters: string | null;
}

const ALL_DETACHED: HomeType[] = ["single_family", "townhouse", "multi_family", "mobile_home"];
const ALL_WITH_YARD: HomeType[] = ["single_family", "townhouse", "multi_family"];
const ALL_HOMES: HomeType[] = ["single_family", "townhouse", "condo", "apartment", "multi_family", "mobile_home"];
const HOUSES_ONLY: HomeType[] = ["single_family", "multi_family", "mobile_home"];

// ═══════════════════════════════════════════════════════════════════════════
// HVAC
// ═══════════════════════════════════════════════════════════════════════════

const hvacTemplates: TaskTemplate[] = [
  {
    id: "hvac-replace-filter",
    name: "Replace HVAC Air Filter",
    description: "Replace the air filter in your HVAC system. Check the size printed on the existing filter before buying a replacement.",
    category: "hvac",
    priority: "efficiency",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 500,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: ["furnace", "ac_unit"],
    seasonalMonths: [],
    healthCategories: ["clean_air"],
    tips: "If you have pets, allergies, or live in a dusty area, replace every 1-2 months instead. MERV 8-11 filters are a good balance of filtration and airflow for most homes. Write the date on the filter edge with a marker.",
    whyItMatters: "A clogged filter forces your system to work harder, increasing energy bills by 5-15%. It also leads to poor air quality and can shorten your HVAC system's lifespan by years.",
  },
  {
    id: "hvac-tuneup-heating",
    name: "Professional Heating Tune-Up",
    description: "Schedule a professional HVAC technician to inspect and tune up your heating system before winter.",
    category: "hvac",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 90,
    estimatedCostLow: 8000,
    estimatedCostHigh: 15000,
    diyDifficulty: "professional",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: ["furnace"],
    seasonalMonths: [9, 10],
    healthCategories: ["clean_air"],
    tips: "Book in September before the rush. Many HVAC companies offer service plans that include two tune-ups per year at a discount. Ask them to check for carbon monoxide leaks.",
    whyItMatters: "Annual tune-ups catch small problems before they become emergency repairs in the middle of winter. A well-maintained furnace lasts 15-20 years versus 10-12 without maintenance.",
  },
  {
    id: "hvac-tuneup-cooling",
    name: "Professional Cooling Tune-Up",
    description: "Schedule a professional HVAC technician to inspect and tune up your air conditioning system before summer.",
    category: "hvac",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 90,
    estimatedCostLow: 8000,
    estimatedCostHigh: 15000,
    diyDifficulty: "professional",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: ["ac_unit"],
    seasonalMonths: [3, 4],
    healthCategories: ["clean_air"],
    tips: "Book in March or April. The technician should check refrigerant levels, clean the evaporator coil, and test the thermostat calibration.",
    whyItMatters: "Low refrigerant or a dirty evaporator coil can increase cooling costs by 20-30% and lead to compressor failure — a $2,000-5,000 repair.",
  },
  {
    id: "hvac-clean-condenser",
    name: "Clean Outdoor Condenser Unit",
    description: "Remove debris, leaves, and dirt from the outdoor AC condenser unit. Gently rinse coils with a garden hose from the inside out.",
    category: "hvac",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: ["ac_unit"],
    seasonalMonths: [4, 5],
    healthCategories: ["clean_air"],
    tips: "Turn off the unit at the breaker first. Keep at least 2 feet of clearance around the unit year-round. Never use a pressure washer — it will bend the fins.",
    whyItMatters: "A dirty condenser has to work much harder to release heat, significantly increasing energy costs and reducing the lifespan of the compressor.",
  },
  {
    id: "hvac-condensate-drain",
    name: "Clear Condensate Drain Line",
    description: "Flush the AC condensate drain line with a cup of distilled white vinegar or a commercial drain treatment to prevent clogs.",
    category: "hvac",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: ["ac_unit"],
    seasonalMonths: [4, 10],
    healthCategories: ["mold_prevention"],
    tips: "The drain line is usually a PVC pipe near your indoor unit. Pour 1 cup of vinegar into the access point. If you see water stains on the ceiling below your unit, the drain may already be clogged.",
    whyItMatters: "A clogged condensate drain is the #1 cause of water damage from HVAC systems. It can ruin ceilings, walls, and flooring — repairs often run $1,000-5,000+.",
  },
  {
    id: "hvac-duct-cleaning",
    name: "Professional Duct Cleaning",
    description: "Hire a professional to clean your HVAC ductwork. This removes accumulated dust, pet dander, mold spores, and other debris.",
    category: "hvac",
    priority: "efficiency",
    frequencyValue: 4,
    frequencyUnit: "years",
    estimatedMinutes: 240,
    estimatedCostLow: 30000,
    estimatedCostHigh: 60000,
    diyDifficulty: "professional",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["clean_air"],
    tips: "Get quotes from at least 3 companies. Beware of $99 whole-house deals — reputable companies charge $300-600. Ask if they use negative pressure equipment. Check NADCA certification.",
    whyItMatters: "Dirty ducts circulate dust, allergens, and potentially mold throughout your home. If anyone in your household has allergies or asthma, this is especially important.",
  },
  {
    id: "hvac-thermostat-batteries",
    name: "Replace Thermostat Batteries",
    description: "Replace batteries in your thermostat to prevent it from losing programming or shutting off your system.",
    category: "hvac",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 5,
    estimatedCostLow: 200,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: [],
    seasonalMonths: [10],
    healthCategories: [],
    tips: "Most thermostats use AA or AAA batteries. Smart thermostats with C-wires may not need batteries. If your thermostat display is dim or blank, batteries are likely dead.",
    whyItMatters: "Dead thermostat batteries mean no heat or AC. This often happens at the worst time — during extreme temperatures when the system is running hard.",
  },
  {
    id: "hvac-inspect-ductwork",
    name: "Inspect Ductwork for Leaks",
    description: "Visually inspect accessible ductwork in your attic, basement, or crawlspace for disconnections, gaps, or damaged insulation.",
    category: "hvac",
    priority: "efficiency",
    frequencyValue: 2,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["hvac"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["clean_air"],
    tips: "Turn the system on and feel for air escaping at joints. Look for duct tape (ironically, it fails on ducts) — metal tape or mastic sealant is what should be used. Seal any leaks you find with foil-backed tape.",
    whyItMatters: "Leaky ducts can waste 20-30% of your heating and cooling energy. That translates to hundreds of dollars per year in wasted utility costs.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// PLUMBING
// ═══════════════════════════════════════════════════════════════════════════

const plumbingTemplates: TaskTemplate[] = [
  {
    id: "plumbing-flush-water-heater",
    name: "Flush Water Heater",
    description: "Drain and flush your water heater tank to remove sediment buildup from the bottom of the tank.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 45,
    estimatedCostLow: 0,
    estimatedCostHigh: 20000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["water_heater"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Attach a garden hose to the drain valve at the bottom of the tank and run it outside or to a floor drain. Turn off the gas/power first. Let the water run until it's clear. If sediment is caked, you may need to partially fill and drain several times.",
    whyItMatters: "Sediment insulates the bottom of the tank from the burner, making it work harder and eventually causing premature tank failure. A new water heater costs $800-2,500 installed.",
  },
  {
    id: "plumbing-test-tpr-valve",
    name: "Test Water Heater Pressure Relief Valve",
    description: "Lift and release the TPR (temperature-pressure relief) valve lever to verify it opens and closes properly.",
    category: "plumbing",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["water_heater"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Place a bucket under the discharge pipe first. Lift the lever briefly — you should hear water flow. If it doesn't release water, or continues dripping after you release, the valve needs replacement ($20 part, easy DIY or ~$150 for a plumber).",
    whyItMatters: "The TPR valve is a critical safety device. If it fails and pressure builds up in the tank, the water heater can literally explode. This is not theoretical — it happens.",
  },
  {
    id: "plumbing-check-toilets",
    name: "Check Toilets for Leaks",
    description: "Add a few drops of food coloring to each toilet tank. Wait 15 minutes without flushing. If color appears in the bowl, the flapper is leaking.",
    category: "plumbing",
    priority: "efficiency",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: [],
    tips: "A leaking flapper wastes 200+ gallons of water per day. Replacement flappers cost $5-10 at any hardware store and take 5 minutes to install. Also check for water around the base — this indicates a failed wax ring.",
    whyItMatters: "A silent toilet leak can waste 6,000+ gallons per month, adding $50-100+ to your water bill. A failed wax ring can rot your subfloor — a much more expensive repair.",
  },
  {
    id: "plumbing-clean-aerators",
    name: "Clean Faucet Aerators",
    description: "Unscrew the aerator from each faucet, soak in vinegar to dissolve mineral buildup, scrub with a toothbrush, and reinstall.",
    category: "plumbing",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Use pliers with a cloth to avoid scratching the finish. If the aerator is stuck, wrap it in a vinegar-soaked rag for 30 minutes first. If the screen is damaged, replacements are $3-5.",
    whyItMatters: "Clogged aerators reduce water pressure and can cause faucets to spray erratically. They also harbor bacteria if mineral deposits build up.",
  },
  {
    id: "plumbing-inspect-washer-hoses",
    name: "Inspect Washing Machine Hoses",
    description: "Check hot and cold supply hoses behind your washing machine for bulges, cracks, or signs of wear. Replace rubber hoses with braided stainless steel.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["washing_machine"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Rubber hoses should be replaced every 3-5 years regardless of appearance. Braided stainless steel hoses last much longer. Turn off supply valves when going on vacation.",
    whyItMatters: "Washing machine hose failure is the #2 cause of residential water damage (after frozen pipes). A burst hose can release 500+ gallons per hour into your home.",
  },
  {
    id: "plumbing-drain-treatment",
    name: "Preventive Drain Treatment",
    description: "Pour a bacterial enzyme drain treatment down each drain (kitchen, bathroom sinks, showers) to break down organic buildup.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 500,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Use enzyme-based treatments (Bio-Clean, Green Gobbler), not chemical drain cleaners like Drano — those corrode pipes. Pour it before bed so it can sit overnight. Also pull out pop-up stoppers and remove hair/soap buildup.",
    whyItMatters: "Preventive treatment is much cheaper than emergency drain clearing ($200-500 per visit). Recurring clogs can also indicate deeper sewer line issues.",
  },
  {
    id: "plumbing-insulate-pipes",
    name: "Insulate Exposed Pipes",
    description: "Check that exposed water pipes in the attic, crawlspace, garage, and exterior walls are properly insulated with foam sleeves.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 1000,
    estimatedCostHigh: 5000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: [],
    seasonalMonths: [10, 11],
    healthCategories: ["mold_prevention"],
    tips: "Foam pipe insulation is cheap ($0.50-2 per 6ft section) and just slips on. Pay special attention to pipes near exterior walls, in the attic, and in the garage. On extremely cold nights, also let faucets drip slightly.",
    whyItMatters: "A single burst pipe can cause $5,000-70,000 in water damage. Pipe insulation is one of the cheapest and most effective home protections you can add.",
  },
  {
    id: "plumbing-test-sump-pump",
    name: "Test Sump Pump",
    description: "Pour a bucket of water into the sump pit to verify the pump activates, pumps the water out, and shuts off properly.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: HOUSES_ONLY,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["sump_pump"],
    seasonalMonths: [3, 4],
    healthCategories: [],
    tips: "Test before the rainy season. Check that the discharge pipe exits away from your foundation. Consider a battery backup sump pump — power outages often coincide with storms. Also check the check valve to ensure water doesn't flow back.",
    whyItMatters: "If your sump pump fails during heavy rain, your basement can flood within hours. The average basement flood costs $20,000-50,000 in damage and remediation.",
  },
  {
    id: "plumbing-pump-septic",
    name: "Pump Septic Tank",
    description: "Schedule a professional septic tank pumping service to remove accumulated solids.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 30000,
    estimatedCostHigh: 60000,
    diyDifficulty: "professional",
    applicableHomeTypes: HOUSES_ONLY,
    applicableSystems: ["sewage"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Know where your tank lid is and keep it accessible. Frequency depends on household size — a family of 4 may need pumping every 2-3 years, a couple every 4-5. Keep a record of pumping dates and condition reports.",
    whyItMatters: "An overflowing septic tank can back up into your home or contaminate groundwater. Septic system replacement costs $10,000-30,000. Regular pumping extends the drain field life by decades.",
  },
  {
    id: "plumbing-check-water-pressure",
    name: "Check Water Pressure",
    description: "Use a pressure gauge on an outdoor spigot to test your home's water pressure. Ideal range is 40-60 PSI.",
    category: "plumbing",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 5,
    estimatedCostLow: 800,
    estimatedCostHigh: 800,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "A pressure gauge costs about $8 at any hardware store and screws onto any hose bib. If pressure exceeds 80 PSI, you need a pressure reducing valve. If it's below 40 PSI, check for leaks or contact your water utility.",
    whyItMatters: "High water pressure (above 80 PSI) stresses pipes, fittings, and appliance connections, leading to leaks and premature failure. It also wastes water and energy.",
  },
  {
    id: "plumbing-test-well-water",
    name: "Test Well Water Quality",
    description: "Send a water sample to a certified lab to test for bacteria, nitrates, pH, and other contaminants.",
    category: "plumbing",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 15,
    estimatedCostLow: 5000,
    estimatedCostHigh: 15000,
    diyDifficulty: "easy",
    applicableHomeTypes: HOUSES_ONLY,
    applicableSystems: ["water_source"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: ["clean_water"],
    tips: "Test in spring when contamination risk is highest from snowmelt. At minimum test for coliform bacteria and nitrates. Contact your county health department — many offer free or low-cost testing. Test more frequently if near agriculture or industry.",
    whyItMatters: "Well water is not regulated by the EPA — you are responsible for its safety. Contaminated well water can cause serious illness, especially for children, elderly, and immunocompromised individuals.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// ELECTRICAL
// ═══════════════════════════════════════════════════════════════════════════

const electricalTemplates: TaskTemplate[] = [
  {
    id: "electrical-test-gfci",
    name: "Test GFCI Outlets",
    description: "Press the TEST button on each GFCI outlet, verify power cuts off, then press RESET. Check kitchens, bathrooms, garages, outdoor, and laundry areas.",
    category: "electrical",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["electrical"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "GFCI outlets protect against electrocution near water. If a GFCI won't trip or reset, it needs replacement immediately — this is a $15 part and a straightforward job for someone comfortable with electrical work, or about $100-150 for an electrician.",
    whyItMatters: "GFCI outlets prevent electrocution deaths. The CPSC estimates they prevent 70% of residential electrocution fatalities. A non-functional GFCI provides zero protection.",
  },
  {
    id: "electrical-test-afci",
    name: "Test Arc-Fault Breakers",
    description: "Press the TEST button on each AFCI breaker in your panel to verify it trips. Reset after testing.",
    category: "electrical",
    priority: "safety",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["electrical"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "AFCI breakers are typically found in bedrooms and living areas (required by code since 1999 in bedrooms, expanded since 2014). If a breaker won't test, have an electrician evaluate it.",
    whyItMatters: "AFCI breakers detect electrical arcs that can cause house fires. Arcing faults are a leading cause of residential electrical fires. Testing ensures this critical safety device actually works.",
  },
  {
    id: "electrical-inspect-panel",
    name: "Inspect Electrical Panel",
    description: "Open the panel cover and visually check for signs of corrosion, scorch marks, melted wire insulation, or unusual odors.",
    category: "electrical",
    priority: "safety",
    frequencyValue: 2,
    frequencyUnit: "years",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["electrical"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "DO NOT touch anything inside the panel — just look. If you see any discoloration, smell burning, or hear buzzing, call an electrician immediately. Take a photo of your panel's breaker labels so you have them on your phone.",
    whyItMatters: "Electrical panel issues cause thousands of house fires annually. Certain panels (Federal Pacific, Zinsco) are known fire hazards and should be replaced regardless of appearance.",
  },
  {
    id: "electrical-replace-surge-protectors",
    name: "Replace Surge Protectors",
    description: "Replace power strip surge protectors that are more than 2-3 years old. Surge protectors degrade with each power surge.",
    category: "electrical",
    priority: "prevent_damage",
    frequencyValue: 2,
    frequencyUnit: "years",
    estimatedMinutes: 15,
    estimatedCostLow: 2000,
    estimatedCostHigh: 6000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["electrical"],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Check if the protection indicator light is still on. Many surge protectors continue to function as power strips after protection has worn out, giving a false sense of security. Invest in whole-house surge protection ($200-500 installed) for comprehensive coverage.",
    whyItMatters: "After absorbing multiple surges, protectors stop protecting — but still deliver power. One lightning strike or power grid surge can fry thousands of dollars in electronics and appliances.",
  },
  {
    id: "electrical-check-outdoor-lighting",
    name: "Check Outdoor Lighting",
    description: "Test all exterior lights including porch, garage, walkway, landscape, and security lights. Replace bulbs and clean fixtures.",
    category: "electrical",
    priority: "safety",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["electrical"],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 10],
    healthCategories: ["injury_prevention"],
    tips: "Switch to LED bulbs for 80% energy savings and 15-25 year lifespan. Check that motion sensor lights activate properly. Clean fixtures with a damp cloth to improve brightness. Verify timers/photocells are working.",
    whyItMatters: "Exterior lighting is a primary deterrent against break-ins. Poorly lit walkways are also a fall hazard — especially important for guests and elderly family members.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// SAFETY & DETECTION
// ═══════════════════════════════════════════════════════════════════════════

const safetyTemplates: TaskTemplate[] = [
  {
    id: "safety-test-smoke-detectors",
    name: "Test Smoke Detectors",
    description: "Press and hold the test button on every smoke detector in your home until it beeps.",
    category: "safety",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "You should have detectors in every bedroom, outside each sleeping area, and on every level. If a detector chirps intermittently, it needs new batteries. If it chirps after new batteries, it may need replacement.",
    whyItMatters: "Working smoke detectors cut the risk of dying in a home fire in half. Three out of five fire deaths occur in homes without working smoke alarms.",
  },
  {
    id: "safety-replace-smoke-batteries",
    name: "Replace Smoke Detector Batteries",
    description: "Replace batteries in all smoke and CO detectors. Even hardwired detectors usually have backup batteries.",
    category: "safety",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 15,
    estimatedCostLow: 500,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [11],
    healthCategories: ["fire_safety"],
    tips: "Do this when daylight saving time ends — easy to remember. Use name-brand batteries. Some newer detectors have sealed 10-year lithium batteries that don't need annual replacement — check your model.",
    whyItMatters: "Dead batteries are the most common reason smoke detectors fail to alert during a fire. Most fire deaths occur between 11 PM and 7 AM when people are sleeping.",
  },
  {
    id: "safety-replace-smoke-detectors",
    name: "Replace Smoke Detectors",
    description: "Replace all smoke detectors that are 10+ years old. Check the manufacture date on the back of the unit.",
    category: "safety",
    priority: "safety",
    frequencyValue: 10,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 2000,
    estimatedCostHigh: 8000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "For best protection, use both ionization (fast-flaming fires) and photoelectric (smoldering fires) detectors, or dual-sensor units. Smart detectors (Nest Protect, Kidde) can send alerts to your phone.",
    whyItMatters: "Smoke detectors lose sensitivity over time. After 10 years, they may not detect smoke reliably. The sensor degrades even if the detector appears to work during testing.",
  },
  {
    id: "safety-test-co-detectors",
    name: "Test Carbon Monoxide Detectors",
    description: "Press and hold the test button on every CO detector to verify it alarms properly.",
    category: "safety",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["clean_air"],
    tips: "CO detectors should be on every level and near sleeping areas. CO is heavier than air, so don't mount too high. If you have a gas furnace, water heater, or attached garage, CO detectors are essential. Replace CO detectors every 5-7 years.",
    whyItMatters: "Carbon monoxide is colorless and odorless — you cannot detect it without a working alarm. Over 400 Americans die annually from accidental CO poisoning, and 50,000+ visit the ER.",
  },
  {
    id: "safety-check-fire-extinguishers",
    name: "Check Fire Extinguishers",
    description: "Verify the pressure gauge is in the green zone, the pin is intact, the nozzle is clear, and there's no visible damage or corrosion.",
    category: "safety",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "Keep extinguishers in the kitchen, garage, and near the laundry room at minimum. Everyone in the household should know the PASS technique: Pull pin, Aim low, Squeeze handle, Sweep side to side.",
    whyItMatters: "A small fire can become unsurvivable in under 2 minutes. Having a working extinguisher in reach means the difference between a scare and a disaster.",
  },
  {
    id: "safety-replace-fire-extinguishers",
    name: "Replace Fire Extinguishers",
    description: "Replace disposable fire extinguishers or have rechargeable ones professionally serviced.",
    category: "safety",
    priority: "safety",
    frequencyValue: 12,
    frequencyUnit: "years",
    estimatedMinutes: 15,
    estimatedCostLow: 3000,
    estimatedCostHigh: 8000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "Rechargeable (metal valve) extinguishers can be professionally serviced every 6 years and hydrostatically tested every 12 years. Disposable (plastic valve) should just be replaced. Check the tag for the manufacture or service date.",
    whyItMatters: "Extinguisher chemicals settle and compact over time, potentially preventing the unit from working when needed. An extinguisher that doesn't discharge is useless in an emergency.",
  },
  {
    id: "safety-clean-dryer-vent",
    name: "Clean Dryer Vent Duct",
    description: "Disconnect the dryer vent from the wall and clean the entire duct run from inside the house to the exterior vent hood. Remove all lint buildup.",
    category: "safety",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 45,
    estimatedCostLow: 0,
    estimatedCostHigh: 17000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["dryer"],
    seasonalMonths: [],
    healthCategories: ["clean_air", "fire_safety"],
    tips: "Buy a dryer vent brush kit ($15-25). If your duct run is long or has many bends, hire a professional ($100-170). Warning signs of a clogged vent: clothes take multiple cycles to dry, the top of the dryer is very hot, you smell burning. Replace flexible foil ducts with rigid or semi-rigid metal.",
    whyItMatters: "Dryer fires cause 2,900 house fires and 5 deaths annually in the US. Lint buildup in the vent duct is the leading cause. This is one of the most important maintenance tasks you can do.",
  },
  {
    id: "safety-test-radon",
    name: "Test Radon Levels",
    description: "Place a radon test kit in the lowest livable level of your home for the specified period (short-term: 2-7 days, long-term: 90+ days).",
    category: "safety",
    priority: "safety",
    frequencyValue: 2,
    frequencyUnit: "years",
    estimatedMinutes: 10,
    estimatedCostLow: 1500,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["foundation"],
    applicableApplianceCategories: [],
    seasonalMonths: [1, 2],
    healthCategories: ["clean_air"],
    tips: "Test in winter when windows are typically closed. Test kits are available from your state radon office (often free) or hardware stores ($12-30). If results are 4 pCi/L or higher, install a radon mitigation system ($800-1,500).",
    whyItMatters: "Radon is the #2 cause of lung cancer after smoking. It's a naturally occurring radioactive gas that seeps through foundation cracks. 1 in 15 US homes has elevated radon.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// ROOF & GUTTERS
// ═══════════════════════════════════════════════════════════════════════════

const roofGutterTemplates: TaskTemplate[] = [
  {
    id: "roof-clean-gutters",
    name: "Clean Gutters and Downspouts",
    description: "Remove leaves, debris, and sediment from all gutters. Flush downspouts with a hose to ensure they're clear. Check for proper drainage.",
    category: "roof_gutters",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 120,
    estimatedCostLow: 0,
    estimatedCostHigh: 25000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["roofing"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5, 10, 11],
    healthCategories: ["mold_prevention", "pest_free"],
    tips: "Use a gutter scoop and garden hose. Check that downspouts discharge at least 4-6 feet from the foundation. Consider gutter guards if you have many trees — they reduce but don't eliminate cleaning. Professional cleaning runs $150-250 for most homes.",
    whyItMatters: "Clogged gutters cause water to overflow against the foundation, leading to basement flooding, foundation damage, and fascia rot. Ice dams in winter can damage roofing and cause interior leaks.",
  },
  {
    id: "roof-inspect-roof",
    name: "Inspect Roof",
    description: "Visually inspect the roof from the ground with binoculars or from a ladder. Look for missing, cracked, or curling shingles, damaged flashing, and sagging.",
    category: "roof_gutters",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 30000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["roofing"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: ["injury_prevention"],
    tips: "Use binoculars from the ground for safety. Also check after major storms. Look for dark streaks (algae), granules in gutters (shingle wear), and any moss growth. A professional inspection costs $200-400 and is worth it every few years or before warranty claims.",
    whyItMatters: "A small roof leak can cause thousands in hidden damage to insulation, framing, drywall, and can lead to mold growth. Catching problems early means a $200 repair instead of a $15,000 replacement.",
  },
  {
    id: "roof-check-flashing",
    name: "Check Flashing Around Penetrations",
    description: "Inspect flashing around the chimney, vent pipes, skylights, and where the roof meets walls. Look for gaps, rust, or lifting.",
    category: "roof_gutters",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["roofing"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: [],
    tips: "Most roof leaks originate at flashing points, not the field of shingles. If you see caulk that's cracked or peeling, it needs to be redone. Flashing repairs are typically $200-500 — much cheaper than water damage repairs.",
    whyItMatters: "Flashing is the most vulnerable point on any roof. Failed flashing accounts for the majority of roof leaks and the water damage that follows.",
  },
  {
    id: "roof-trim-overhanging-branches",
    name: "Trim Branches Overhanging Roof",
    description: "Cut back tree branches that hang over or touch the roof. Maintain at least 10 feet of clearance.",
    category: "roof_gutters",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 0,
    estimatedCostHigh: 50000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["roofing"],
    applicableApplianceCategories: [],
    seasonalMonths: [2, 3],
    healthCategories: ["pest_free", "injury_prevention"],
    tips: "Branches touching the roof abrade shingles and provide a highway for pests. Large branches near the house are a risk in storms. For large trees or branches near power lines, hire a certified arborist ($300-2,000+ depending on the job).",
    whyItMatters: "Falling branches during storms are a major cause of roof damage and insurance claims. Overhanging branches also drop debris that clogs gutters and promotes moss growth.",
  },
  {
    id: "roof-inspect-attic",
    name: "Inspect Attic for Leaks and Moisture",
    description: "Enter the attic with a flashlight. Look for daylight through the roof, water stains, damp insulation, and signs of mold or pests.",
    category: "roof_gutters",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["roofing"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 10],
    healthCategories: ["clean_air", "mold_prevention", "pest_free"],
    tips: "Check after heavy rains. Look for black mold on roof sheathing — this indicates chronic moisture. Ensure bathroom exhaust fans vent outside, not into the attic. Check that soffit vents aren't blocked by insulation.",
    whyItMatters: "Attic moisture problems lead to mold, rotted framing, and ruined insulation. These issues are invisible from outside and can develop into major structural and health problems.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// EXTERIOR
// ═══════════════════════════════════════════════════════════════════════════

const exteriorTemplates: TaskTemplate[] = [
  {
    id: "exterior-power-wash-siding",
    name: "Power Wash Siding",
    description: "Power wash the exterior siding of your home to remove dirt, mildew, and algae buildup.",
    category: "exterior",
    priority: "cosmetic",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 180,
    estimatedCostLow: 0,
    estimatedCostHigh: 40000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: [],
    tips: "Use 1,500-2,000 PSI for vinyl siding, lower for wood. Keep the nozzle 12+ inches from the surface. Never aim up under siding — water will get behind it. Rent a power washer for $50-100/day, or hire a pro for $200-400.",
    whyItMatters: "Beyond curb appeal, mildew and algae growth can degrade siding over time. Clean siding also makes it easier to spot damage that needs repair.",
  },
  {
    id: "exterior-power-wash-hardscape",
    name: "Power Wash Driveway and Walkways",
    description: "Power wash concrete or paver driveway, walkways, and patio surfaces.",
    category: "exterior",
    priority: "cosmetic",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 120,
    estimatedCostLow: 0,
    estimatedCostHigh: 30000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: ["injury_prevention"],
    tips: "Use 3,000+ PSI for concrete. A surface cleaner attachment ($30-60) makes driveways much faster and more uniform than a wand. Pre-treat oil stains with degreaser. For pavers, re-sand joints after washing.",
    whyItMatters: "Mold, mildew, and algae on walkways create a slip hazard. Organic growth can also work into concrete cracks and accelerate deterioration.",
  },
  {
    id: "exterior-recaulk",
    name: "Inspect and Re-Caulk Windows and Doors",
    description: "Check all exterior caulking around windows, doors, and trim. Remove cracked or peeling caulk and apply fresh exterior-grade caulk.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 1000,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [9, 10],
    healthCategories: ["mold_prevention"],
    tips: "Use silicone or polyurethane caulk for exterior — it stays flexible. Don't caulk the bottom of window frames — that's a weep channel for moisture escape. Apply on a dry day above 40°F. A caulk gun and tube costs under $15.",
    whyItMatters: "Failed caulk lets water behind siding and into wall cavities, causing rot, mold, and insulation damage that's expensive to repair and invisible until advanced.",
  },
  {
    id: "exterior-touch-up-paint",
    name: "Touch Up Exterior Paint",
    description: "Inspect exterior painted surfaces for peeling, cracking, or bare wood. Sand, prime, and repaint affected areas.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 120,
    estimatedCostLow: 2000,
    estimatedCostHigh: 10000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [5, 6, 9],
    healthCategories: [],
    tips: "Keep a record of your paint colors and brands. Focus on south and west-facing surfaces which get the most sun damage. Always prime bare wood before painting. Don't paint in direct sunlight or below 50°F.",
    whyItMatters: "Paint is your home's first defense against moisture. Exposed wood absorbs water and rots quickly. Touching up annually prevents the need for a full $5,000-15,000 exterior repaint.",
  },
  {
    id: "exterior-check-grading",
    name: "Check Grading Around Foundation",
    description: "Verify that the ground slopes away from your foundation on all sides. Soil should drop 6 inches over the first 10 feet from the foundation.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 5000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["foundation"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: ["mold_prevention"],
    tips: "Soil settles over time, especially around new construction. Add topsoil to low spots and grade away from the house. Don't pile soil above the siding line. Also check that downspout extensions direct water well away from the foundation.",
    whyItMatters: "Improper grading is the #1 cause of wet basements and foundation problems. Water pooling against the foundation leads to cracks, leaks, and structural damage over time.",
  },
  {
    id: "exterior-inspect-foundation",
    name: "Inspect Foundation for Cracks",
    description: "Walk the perimeter and inspect visible foundation walls for new cracks, shifting, or water stains. Check interior basement walls too.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["foundation"],
    applicableApplianceCategories: [],
    seasonalMonths: [4],
    healthCategories: ["mold_prevention", "pest_free", "injury_prevention"],
    tips: "Hairline cracks are normal. Horizontal cracks, stair-step cracks in block, or cracks wider than 1/4 inch need professional evaluation. Take photos and monitor — if cracks are growing, act quickly. Seal small cracks with hydraulic cement ($10).",
    whyItMatters: "Foundation issues are among the most expensive home repairs ($5,000-30,000+). Catching them early when they're small cracks can save tens of thousands versus waiting until walls are bowing.",
  },
  {
    id: "exterior-seal-deck",
    name: "Clean and Seal Deck",
    description: "Clean the deck surface (power wash or scrub with deck cleaner), let dry completely, then apply sealant or stain.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 240,
    estimatedCostLow: 3000,
    estimatedCostHigh: 15000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [5, 6],
    healthCategories: ["mold_prevention", "injury_prevention"],
    tips: "Test if your deck needs sealing: sprinkle water on it. If it beads up, the seal is still good. If it soaks in, it's time. Let the deck dry 24-48 hours after washing before applying sealer. Apply on a cloudy day to avoid lap marks.",
    whyItMatters: "Unsealed wood decks absorb water, leading to rot, warping, and structural failure. A deck replacement costs $5,000-20,000+. Annual sealing preserves both safety and value.",
  },
  {
    id: "exterior-inspect-fence",
    name: "Inspect Fence Posts and Panels",
    description: "Walk your fence line and check posts for rot (push on them), panels for damage, and gates for proper operation.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [4],
    healthCategories: ["injury_prevention"],
    tips: "Wood posts rot at ground level first — poke with a screwdriver to check for soft spots. A single post replacement is $100-300. Tighten loose hardware on gates. Clear soil and debris away from the bottom of fence panels.",
    whyItMatters: "One rotted post can cause an entire fence section to collapse, especially in wind. Catching rot early means replacing one post instead of rebuilding a whole section.",
  },
  {
    id: "exterior-seal-driveway",
    name: "Seal Asphalt Driveway",
    description: "Apply sealcoat to your asphalt driveway after cleaning and filling any cracks.",
    category: "exterior",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "years",
    estimatedMinutes: 180,
    estimatedCostLow: 5000,
    estimatedCostHigh: 30000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [6, 7, 8],
    healthCategories: [],
    tips: "Fill cracks with crack filler before sealing. Apply on a warm day (50°F+) with no rain expected for 24 hours. Two thin coats are better than one thick coat. A DIY 5-gallon bucket covers about 400 sq ft and costs $15-30. Professional sealing runs $300-600.",
    whyItMatters: "Water seeps into asphalt cracks, freezes, and expands — turning small cracks into potholes. A full driveway replacement costs $3,000-8,000. Sealcoating every 2-3 years can double the driveway's lifespan.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// WINDOWS & DOORS
// ═══════════════════════════════════════════════════════════════════════════

const windowDoorTemplates: TaskTemplate[] = [
  {
    id: "windows-check-weatherstripping",
    name: "Check Weatherstripping",
    description: "Inspect weatherstripping around all exterior doors and operable windows. Replace any that is cracked, compressed, or missing.",
    category: "windows_doors",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 500,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [10],
    healthCategories: [],
    tips: "Close a dollar bill in the door — if it slides out easily, the weatherstripping needs replacement. Self-adhesive foam tape is the easiest fix. V-strip and door sweeps are more durable. Check the bottom of garage doors too.",
    whyItMatters: "Air leaks around doors and windows can account for 25-30% of heating and cooling costs. Good weatherstripping pays for itself within one season.",
  },
  {
    id: "windows-lubricate-hardware",
    name: "Lubricate Door Hinges and Locks",
    description: "Apply lubricant to all door hinges, deadbolts, and lock cylinders. Test operation of all exterior locks.",
    category: "windows_doors",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 500,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Use graphite powder or silicone spray for locks — NOT WD-40, which attracts dust and gums up over time. For hinges, a drop of 3-in-1 oil on each pin works great. Lift the hinge pin slightly to apply.",
    whyItMatters: "Stiff locks can break keys off inside the cylinder — an expensive locksmith call. Squeaky hinges are annoying, but neglected hinges can also wear out the door frame.",
  },
  {
    id: "windows-clean-weep-holes",
    name: "Clean Window Weep Holes",
    description: "Locate and clear the small weep holes at the bottom of window frames. Use a toothpick or compressed air to remove debris.",
    category: "windows_doors",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [4],
    healthCategories: ["mold_prevention"],
    tips: "Weep holes are small slots or holes on the outside bottom of window frames — they let trapped water drain out. Don't seal them. If you can't find them, check your window manufacturer's documentation.",
    whyItMatters: "Blocked weep holes trap water inside the window frame, leading to wood rot, mold growth, and eventual window failure. Window replacement runs $300-1,000+ per window.",
  },
  {
    id: "windows-repair-screens",
    name: "Inspect and Repair Window Screens",
    description: "Check all window and door screens for holes, tears, or damaged frames. Repair or replace as needed.",
    category: "windows_doors",
    priority: "cosmetic",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 4],
    healthCategories: [],
    tips: "Small holes can be patched with screen repair patches ($5 for a pack). For larger tears, re-screening a frame costs $5-15 in materials and takes 20 minutes with a spline roller. Most hardware stores will re-screen for you for $10-20 per screen.",
    whyItMatters: "Damaged screens let in mosquitoes, flies, and other pests. They also reduce your home's curb appeal and can affect resale value.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// APPLIANCES
// ═══════════════════════════════════════════════════════════════════════════

const applianceTemplates: TaskTemplate[] = [
  {
    id: "appliance-fridge-coils",
    name: "Clean Refrigerator Condenser Coils",
    description: "Vacuum or brush the condenser coils on the back or bottom of your refrigerator to remove dust buildup.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["refrigerator"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Unplug the fridge first. Coils are usually behind a removable panel on the bottom front or on the back. Use a coil cleaning brush ($8) or vacuum with a crevice attachment. If you have pets, do this every 3 months — pet hair clogs coils fast.",
    whyItMatters: "Dusty coils make the compressor work up to 25% harder, shortening its life and increasing energy costs by $100+/year. The compressor is the most expensive part — $500-1,000 to replace.",
  },
  {
    id: "appliance-fridge-water-filter",
    name: "Replace Refrigerator Water Filter",
    description: "Replace the water filter in your refrigerator according to manufacturer recommendations.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 2000,
    estimatedCostHigh: 5000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["refrigerator"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Note your filter model number — it's usually printed on the existing filter. Aftermarket filters are often half the price of OEM and work fine. Run 2-3 gallons through a new filter before drinking the water.",
    whyItMatters: "An old filter loses effectiveness and can actually harbor bacteria. Water taste and quality deteriorate, and the ice maker may produce smaller or cloudy ice.",
  },
  {
    id: "appliance-fridge-door-seals",
    name: "Check Refrigerator Door Seals",
    description: "Inspect the rubber gaskets around fridge and freezer doors for cracks, tears, or gaps. Clean with warm soapy water.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["refrigerator"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Close the door on a dollar bill — if it slides out easily, the seal is worn. Clean sticky or dirty seals with warm water and baking soda. Apply a thin layer of petroleum jelly to keep seals supple. Replacement gaskets cost $50-150.",
    whyItMatters: "A leaking door seal forces the compressor to run constantly, dramatically increasing energy costs and wearing out the compressor faster.",
  },
  {
    id: "appliance-dishwasher-filter",
    name: "Clean Dishwasher Filter",
    description: "Remove and clean the dishwasher filter at the bottom of the tub. Rinse under running water and scrub with a soft brush.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["dishwasher"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "The filter is usually a twist-and-pull cylinder at the bottom of the tub. Most modern dishwashers have a manual filter (older ones had self-cleaning grinders). If dishes are coming out gritty or smelly, the filter is likely overdue.",
    whyItMatters: "A clogged filter means food particles recirculate onto your \"clean\" dishes. It also strains the pump motor and can cause drainage issues and bad odors.",
  },
  {
    id: "appliance-dishwasher-clean-cycle",
    name: "Run Dishwasher Cleaning Cycle",
    description: "Place a cup of white vinegar on the top rack and run a hot cycle. Then sprinkle baking soda on the bottom and run a short hot cycle.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["dishwasher"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "You can also use dishwasher cleaning tablets (Affresh, Finish). Clean the spray arm holes with a toothpick if you notice reduced water pressure. Wipe down the door edges and rubber gasket — these areas don't get cleaned during cycles.",
    whyItMatters: "Mineral deposits, grease, and food residue build up inside the dishwasher, reducing cleaning effectiveness and eventually clogging spray arms and the drain.",
  },
  {
    id: "appliance-washer-clean",
    name: "Clean Washing Machine",
    description: "Run a hot cleaning cycle with washing machine cleaner or 2 cups of white vinegar. Wipe down the door seal, detergent dispenser, and drum.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["washing_machine"],
    seasonalMonths: [],
    healthCategories: ["mold_prevention"],
    tips: "Front-loaders are especially prone to mold and mildew. Always leave the door ajar after use to let it dry. Pull back the rubber gasket on front-loaders and wipe out trapped moisture and debris. Don't use too much detergent — it causes buildup.",
    whyItMatters: "Mold and mildew in washing machines transfer to your clothes, causing musty odors. In front-loaders, mold behind the gasket can become a health concern.",
  },
  {
    id: "appliance-washer-door-seal",
    name: "Inspect Washing Machine Door Seal",
    description: "Pull back the rubber door gasket on front-loading washers and inspect for mold, debris, and damage.",
    category: "appliance",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["washing_machine"],
    seasonalMonths: [],
    healthCategories: ["mold_prevention"],
    tips: "Clean mold with a solution of equal parts water and vinegar or a dilute bleach solution. Small items (socks, baby clothes) often get trapped behind the gasket. If the gasket is torn or no longer seals, replacement costs $150-300 in parts.",
    whyItMatters: "A damaged door seal causes leaks during wash cycles, potentially damaging your floor. Mold behind the gasket is a common source of musty-smelling laundry.",
  },
  {
    id: "appliance-dryer-deep-clean",
    name: "Deep Clean Dryer Lint Trap Area",
    description: "Remove the lint trap and vacuum deep into the lint trap housing. Also clean under and behind the dryer.",
    category: "appliance",
    priority: "safety",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["dryer"],
    seasonalMonths: [],
    healthCategories: ["fire_safety"],
    tips: "Use a long, narrow vacuum attachment or a dryer lint brush ($8) to reach deep into the housing. If your lint screen has fabric softener residue (run water over it — if water pools, it has residue), scrub with hot soapy water and a brush.",
    whyItMatters: "Lint that bypasses the trap accumulates in the housing and around the heating element — a direct fire hazard. This supplements but doesn't replace annual vent duct cleaning.",
  },
  {
    id: "appliance-disposal-clean",
    name: "Clean Garbage Disposal",
    description: "Grind ice cubes and citrus peels, then flush with cold water. For deeper cleaning, use baking soda and vinegar.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["garbage_disposal"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Never put grease, fibrous vegetables (celery, artichokes), or pasta/rice (they expand) down the disposal. Always run cold water when operating the disposal. If it's jammed, use the hex wrench that came with it (usually fits a hole on the bottom).",
    whyItMatters: "A neglected garbage disposal develops odors from bacterial buildup on food residue. Infrequent use can also cause the impellers to seize from corrosion.",
  },
  {
    id: "appliance-range-hood-filter",
    name: "Replace or Clean Range Hood Filter",
    description: "Remove the range hood filter and either replace it (charcoal filters) or clean it (metal mesh filters) in hot soapy water or the dishwasher.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: ["oven_range"],
    seasonalMonths: [],
    healthCategories: ["clean_air", "fire_safety"],
    tips: "For metal mesh filters, soak in very hot water with degreasing dish soap or boil with baking soda. Charcoal/carbon filters cannot be cleaned — replace them. If you cook frequently with oil, clean monthly.",
    whyItMatters: "A grease-clogged range hood filter is ineffective at removing cooking fumes and is also a fire hazard. Grease buildup can ignite from heat below.",
  },
  {
    id: "appliance-water-softener-salt",
    name: "Add Salt to Water Softener",
    description: "Check the water softener brine tank and add salt as needed. Keep the tank at least 1/3 full.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 500,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["water_softener"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Use solar or evaporated salt pellets — avoid rock salt which leaves more residue. Don't overfill past 2/3. If you see a hard crust (salt bridge) above the water line, break it up with a broom handle. Check that the salt isn't mushing into a solid mass at the bottom.",
    whyItMatters: "Without salt, the softener can't regenerate and your water goes hard. Hard water causes scale buildup in pipes and appliances, reducing their efficiency and lifespan significantly.",
  },
  {
    id: "appliance-water-softener-clean",
    name: "Clean Water Softener Brine Tank",
    description: "Empty the brine tank, scrub the interior, and remove any salt bridges or mushing. Reassemble and refill with salt.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["water_softener"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Let the salt level run low before cleaning to make it easier. Scrub with warm water and dish soap. Rinse thoroughly. Check the brine well tube and float valve while you're in there.",
    whyItMatters: "Sediment, dirt, and insoluble salt residue accumulate at the bottom of the brine tank, reducing regeneration efficiency and potentially fouling the resin bed.",
  },
  {
    id: "appliance-water-filter-replace",
    name: "Replace Whole-House Water Filter",
    description: "Replace the cartridge in your whole-house water filtration system according to manufacturer specifications.",
    category: "appliance",
    priority: "efficiency",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 2000,
    estimatedCostHigh: 8000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: ["plumbing"],
    applicableApplianceCategories: ["water_filter"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Turn off the water supply before changing the filter. Keep a spare filter on hand so you can replace immediately when needed. Note your filter size and type — they're not interchangeable. Lubricate the O-ring with food-grade silicone when reassembling.",
    whyItMatters: "An exhausted filter stops removing contaminants and can actually release trapped particles back into your water. Severely clogged filters also reduce water pressure throughout the house.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// LAWN & LANDSCAPE
// ═══════════════════════════════════════════════════════════════════════════

const lawnTemplates: TaskTemplate[] = [
  {
    id: "lawn-fertilize",
    name: "Fertilize Lawn",
    description: "Apply appropriate seasonal fertilizer to your lawn using a broadcast spreader.",
    category: "lawn_landscape",
    priority: "cosmetic",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 30,
    estimatedCostLow: 2000,
    estimatedCostHigh: 5000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 4, 6, 9],
    healthCategories: [],
    tips: "Get a soil test first ($15-30 through your county extension office) to know what nutrients you actually need. More is NOT better — over-fertilizing burns grass and pollutes waterways. Water within 24 hours of application. Apply in the morning or evening, never in the heat of the day.",
    whyItMatters: "Proper fertilization promotes dense, healthy grass that naturally crowds out weeds and resists disease and drought, reducing the need for herbicides and extra watering.",
  },
  {
    id: "lawn-aerate",
    name: "Aerate Lawn",
    description: "Use a core aerator to remove small plugs of soil across your lawn, reducing compaction and improving water and nutrient penetration.",
    category: "lawn_landscape",
    priority: "cosmetic",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 0,
    estimatedCostHigh: 20000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [9, 10],
    healthCategories: [],
    tips: "Rent a core aerator from a home improvement store ($70-90/day) — spike aerators don't work nearly as well. Mark sprinkler heads and shallow utility lines first. Water the lawn the day before to soften the soil. Leave the soil plugs on the lawn — they'll break down naturally.",
    whyItMatters: "Compacted soil prevents water, air, and nutrients from reaching grass roots. Aeration is the single most impactful thing you can do for lawn health after proper watering.",
  },
  {
    id: "lawn-irrigation-startup",
    name: "Spring Irrigation System Startup",
    description: "Gradually open the main valve, pressurize the system slowly, and run each zone to check for broken heads, leaks, and coverage issues.",
    category: "lawn_landscape",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 45,
    estimatedCostLow: 0,
    estimatedCostHigh: 15000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: ["irrigation"],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: [],
    tips: "Open the main valve SLOWLY (quarter-turn at a time over 10 minutes) to avoid water hammer that can crack pipes. Walk each zone while it runs — look for geysers (broken heads), sunken heads, and dry spots. Adjust heads for coverage. Replace broken heads ($3-10 each).",
    whyItMatters: "Freeze damage from winter can crack pipes and heads. Discovering this early prevents water waste, landscape damage, and high water bills from undetected leaks.",
  },
  {
    id: "lawn-irrigation-winterize",
    name: "Winterize Irrigation System",
    description: "Blow out all irrigation lines with compressed air to prevent freeze damage. Shut off the irrigation water supply.",
    category: "lawn_landscape",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 0,
    estimatedCostHigh: 12000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: ["irrigation"],
    applicableApplianceCategories: [],
    seasonalMonths: [10, 11],
    healthCategories: [],
    tips: "You need an air compressor with at least 80 PSI and adequate CFM. Don't exceed 50 PSI for PVC systems or 80 PSI for polyethylene. Blow out each zone twice. Many irrigation companies offer winterization for $50-120 — worth it if you're not comfortable with compressors.",
    whyItMatters: "Water left in irrigation lines freezes and expands, cracking pipes and fittings. Repair costs typically run $200-1,000+ in spring, and you'll have no irrigation until it's fixed.",
  },
  {
    id: "lawn-mulch-beds",
    name: "Mulch Garden Beds",
    description: "Apply 2-3 inches of fresh mulch to all garden beds, keeping mulch 3 inches away from tree trunks and plant stems.",
    category: "lawn_landscape",
    priority: "cosmetic",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 120,
    estimatedCostLow: 5000,
    estimatedCostHigh: 20000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [4, 5],
    healthCategories: [],
    tips: "Don't pile mulch against tree trunks (\"volcano mulching\") — it causes rot. Calculate needs: 1 cubic yard covers 100 sq ft at 3 inches deep. Bulk mulch delivered is much cheaper than bags ($30-50/yard delivered vs $4-5/bag). Edge beds first for a clean look.",
    whyItMatters: "Mulch suppresses weeds, retains soil moisture (reducing watering by 25-50%), moderates soil temperature, and adds organic matter as it decomposes.",
  },
  {
    id: "lawn-sharpen-mower",
    name: "Sharpen Mower Blades",
    description: "Remove and sharpen or replace lawn mower blades. Balance the blade after sharpening.",
    category: "lawn_landscape",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 4],
    healthCategories: [],
    tips: "Disconnect the spark plug before working on blades. Use a file or bench grinder. Balance the blade on a nail — if one side dips, sharpen that side more. New blades are $15-30 if sharpening isn't worth the effort. Many hardware stores offer sharpening for $10-15.",
    whyItMatters: "Dull blades tear grass instead of cutting it, leaving ragged brown tips that invite disease. A clean cut promotes denser, healthier growth and a better-looking lawn.",
  },
  {
    id: "lawn-trim-trees",
    name: "Trim Trees",
    description: "Hire a certified arborist to prune dead, diseased, or hazardous branches from your trees. Remove suckers and water sprouts.",
    category: "lawn_landscape",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "years",
    estimatedMinutes: 240,
    estimatedCostLow: 30000,
    estimatedCostHigh: 150000,
    diyDifficulty: "professional",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [1, 2, 3],
    healthCategories: ["injury_prevention"],
    tips: "Prune in late winter when trees are dormant (except for spring-flowering trees — prune those right after blooming). Never hire anyone who suggests topping a tree — it's destructive and encourages weak growth. Get ISA-certified arborists. Get 3 quotes.",
    whyItMatters: "Dead branches are unpredictable and can fall on people, cars, or structures. Proper pruning also prevents disease spread, improves tree health, and reduces storm damage risk.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// PEST CONTROL
// ═══════════════════════════════════════════════════════════════════════════

const pestTemplates: TaskTemplate[] = [
  {
    id: "pest-termite-inspection",
    name: "Termite Inspection",
    description: "Schedule a professional termite inspection. Inspector will check for signs of termites, carpenter ants, and wood-destroying organisms.",
    category: "pest_control",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 5000,
    estimatedCostHigh: 15000,
    diyDifficulty: "professional",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["foundation"],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 4],
    healthCategories: ["pest_free"],
    tips: "Many pest companies offer free inspections hoping to sell treatment. Get at least 2 opinions before committing to treatment. Look for mud tubes on foundations yourself — pencil-width tubes running from soil up the foundation wall. Termite damage is often NOT covered by homeowner's insurance.",
    whyItMatters: "Termites cause $5 billion in property damage annually in the US. An active colony can eat a linear foot of 2x4 in about 5 months. Damage is often hidden inside walls and undetected for years.",
  },
  {
    id: "pest-seal-entry-points",
    name: "Seal Entry Points Walkthrough",
    description: "Walk the exterior of your home and seal gaps, cracks, and openings that pests could use to enter. Check where utilities penetrate walls.",
    category: "pest_control",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 1000,
    estimatedCostHigh: 3000,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [9, 10],
    healthCategories: ["pest_free"],
    tips: "A mouse can fit through a hole the size of a dime. Check around pipes, cables, vents, and where siding meets the foundation. Use steel wool and caulk for small gaps (mice can't chew through steel wool). Use copper mesh for larger holes. Don't forget the garage door seal.",
    whyItMatters: "Prevention is far more effective and cheaper than extermination. Mice and rats can chew through wiring (fire hazard), contaminate food, and cause significant property damage.",
  },
  {
    id: "pest-mosquito-check",
    name: "Mosquito Prevention — Standing Water Check",
    description: "Walk your property and eliminate all standing water sources: bird baths, clogged gutters, plant saucers, tarps, tires, toys.",
    category: "pest_control",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_WITH_YARD,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [5, 6, 7, 8, 9],
    healthCategories: ["pest_free"],
    tips: "Mosquitoes only need a bottle cap of water to breed. Change bird bath water weekly. Add mosquito dunks (BTI) to ponds and rain barrels — they're safe for wildlife but kill larvae. Check spots after rain: tarps that collect water, low spots in yard, and clogged drainage.",
    whyItMatters: "Beyond being a nuisance, mosquitoes transmit West Nile virus, Zika, and other diseases. Reducing breeding sites is the most effective control method.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// GARAGE
// ═══════════════════════════════════════════════════════════════════════════

const garageTemplates: TaskTemplate[] = [
  {
    id: "garage-lubricate-door",
    name: "Lubricate Garage Door Tracks and Hardware",
    description: "Apply lithium or silicone lubricant to garage door tracks, rollers, hinges, and springs. Also lubricate the opener chain or screw drive.",
    category: "garage",
    priority: "prevent_damage",
    frequencyValue: 6,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 500,
    estimatedCostHigh: 500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: ["garage_door"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "Use white lithium grease or silicone spray — NOT WD-40 (it's a solvent, not a lubricant). Spray the roller stems, hinge pivot points, and spring coils. Wipe excess from the tracks. NEVER attempt to adjust or replace the torsion springs yourself — they're under extreme tension and can kill.",
    whyItMatters: "A well-lubricated garage door operates quieter, puts less strain on the opener motor, and prevents premature wear on expensive components like springs ($200-400 to replace professionally).",
  },
  {
    id: "garage-test-auto-reverse",
    name: "Test Garage Door Auto-Reverse Safety",
    description: "Place a 2x4 flat on the ground in the door's path and close the door. It should reverse immediately upon contact. Also test the photo-eye sensors.",
    category: "garage",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 5,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: ["garage_door"],
    seasonalMonths: [],
    healthCategories: ["injury_prevention"],
    tips: "Test the pressure reverse (2x4 test) and the photo-eye reverse (wave your foot through the beam). Both should cause immediate reversal. Clean the photo-eye lenses with a soft cloth if they're not working. If either test fails, do not use the door until it's repaired.",
    whyItMatters: "Garage doors weigh 150-400 pounds and exert hundreds of pounds of force. A door that doesn't auto-reverse can crush a child, pet, or person. This is a critical safety check.",
  },
  {
    id: "garage-replace-weather-seal",
    name: "Replace Garage Door Weather Seal",
    description: "Inspect and replace the rubber weather seal at the bottom of the garage door and the weatherstripping around the sides and top.",
    category: "garage",
    priority: "efficiency",
    frequencyValue: 2,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 1500,
    estimatedCostHigh: 3500,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: [],
    applicableApplianceCategories: ["garage_door"],
    seasonalMonths: [10],
    healthCategories: [],
    tips: "The bottom seal slides into a channel on the bottom of the door — measure the width of the channel before buying. Side and top seals are usually adhesive-backed. If daylight is visible around the closed door, the seals need replacing.",
    whyItMatters: "Worn weather seals let in rain, snow, insects, and rodents. They also waste energy if you have a heated garage or rooms above it. Cold air infiltration affects the entire house.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// POOL
// ═══════════════════════════════════════════════════════════════════════════

const poolTemplates: TaskTemplate[] = [
  {
    id: "pool-test-chemicals",
    name: "Test Pool Chemical Balance",
    description: "Test pH, chlorine, alkalinity, and calcium hardness. Adjust chemicals as needed to maintain safe swimming conditions.",
    category: "pool",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "weeks",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 3000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["pool"],
    applicableApplianceCategories: ["pool_pump"],
    seasonalMonths: [5, 6, 7, 8, 9],
    healthCategories: ["clean_water"],
    tips: "Target pH: 7.2-7.6, Free chlorine: 1-3 ppm, Alkalinity: 80-120 ppm. Test strips are convenient but liquid test kits are more accurate. Test more frequently after heavy rain, heavy use, or extreme heat. Take a water sample to your pool store monthly for a comprehensive analysis.",
    whyItMatters: "Imbalanced pool water can cause skin and eye irritation, promote algae and bacteria growth, and damage pool surfaces and equipment. Low chlorine can allow dangerous pathogens.",
  },
  {
    id: "pool-clean-filter",
    name: "Clean Pool Filter",
    description: "Clean or backwash the pool filter depending on type (cartridge, sand, or DE). Replace cartridges or DE powder as needed.",
    category: "pool",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 5000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["pool"],
    applicableApplianceCategories: ["pool_pump"],
    seasonalMonths: [5, 6, 7, 8, 9],
    healthCategories: [],
    tips: "Clean when filter pressure reads 8-10 PSI above the clean baseline. For cartridge filters, soak overnight in filter cleaner solution. Sand filters should be backwashed when pressure rises. Replace cartridges every 1-2 years depending on use.",
    whyItMatters: "A dirty filter can't clean the water effectively, leading to cloudy or green water and potential health hazards. It also forces the pump to work harder, increasing energy costs and wear.",
  },
  {
    id: "pool-open-season",
    name: "Open Pool for Season",
    description: "Remove the cover, reconnect equipment, fill to proper level, balance chemicals, clean surfaces, and run the pump.",
    category: "pool",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 180,
    estimatedCostLow: 10000,
    estimatedCostHigh: 40000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["pool"],
    applicableApplianceCategories: ["pool_pump"],
    seasonalMonths: [4, 5],
    healthCategories: [],
    tips: "Open when water temperature consistently stays above 60°F. Remove, clean, and properly store the cover. Inspect all equipment before turning on. Prime the pump before starting. Shock the pool with high chlorine. Run the pump 24 hours initially. A professional pool opening costs $200-400.",
    whyItMatters: "Proper opening prevents equipment damage and gets the water chemistry right from the start, avoiding weeks of fighting algae and cloudy water.",
  },
  {
    id: "pool-close-season",
    name: "Close Pool for Season",
    description: "Balance chemistry, lower water level, blow out plumbing lines, add winterizing chemicals, install the cover.",
    category: "pool",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 180,
    estimatedCostLow: 10000,
    estimatedCostHigh: 40000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ALL_DETACHED,
    applicableSystems: ["pool"],
    applicableApplianceCategories: ["pool_pump"],
    seasonalMonths: [10, 11],
    healthCategories: [],
    tips: "Balance chemistry before closing — it's much harder to fix in spring if wrong. Lower water below skimmer level. Blow out all plumbing lines with a shop vac or compressor and plug them. Remove and store pump drain plugs. Use a quality winter cover with a tight fit.",
    whyItMatters: "Water left in plumbing lines freezes and cracks pipes and fittings — repairs can cost $500-2,000+. Improper closing also leads to staining and an expensive, difficult opening in spring.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// HOT TUB
// ═══════════════════════════════════════════════════════════════════════════

const hotTubTemplates: TaskTemplate[] = [
  {
    id: "hottub-test-chemicals",
    name: "Test Hot Tub Water Chemistry",
    description: "Test pH, alkalinity, and sanitizer levels. Adjust chemicals to maintain safe soaking conditions.",
    category: "pool",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "weeks",
    estimatedMinutes: 10,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ["single_family", "townhouse", "multi_family", "mobile_home"],
    applicableSystems: [],
    applicableApplianceCategories: ["hot_tub"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Target pH: 7.2-7.8, Alkalinity: 80-120 ppm, Bromine: 3-5 ppm or Chlorine: 1-3 ppm. Test before each use if used daily. Shock weekly with non-chlorine shock after heavy use.",
    whyItMatters: "Warm water breeds bacteria much faster than pool water. Improperly sanitized hot tubs can cause hot tub folliculitis, Legionnaire's disease, and other infections.",
  },
  {
    id: "hottub-clean-filter",
    name: "Clean Hot Tub Filter",
    description: "Remove the filter cartridge, rinse with a hose, and soak in filter cleaner solution overnight.",
    category: "pool",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "months",
    estimatedMinutes: 15,
    estimatedCostLow: 0,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ["single_family", "townhouse", "multi_family", "mobile_home"],
    applicableSystems: [],
    applicableApplianceCategories: ["hot_tub"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Keep a spare filter so you can swap while the other soaks overnight. Replace filters every 12-18 months depending on use. Rinse weekly if you use the tub frequently.",
    whyItMatters: "A dirty filter can't sanitize effectively, leading to cloudy water and potential health issues. It also strains the pump motor.",
  },
  {
    id: "hottub-drain-refill",
    name: "Drain and Refill Hot Tub",
    description: "Drain the tub completely, clean the shell with a non-abrasive cleaner, flush the plumbing lines, and refill with fresh water.",
    category: "pool",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 120,
    estimatedCostLow: 0,
    estimatedCostHigh: 2000,
    diyDifficulty: "moderate",
    applicableHomeTypes: ["single_family", "townhouse", "multi_family", "mobile_home"],
    applicableSystems: [],
    applicableApplianceCategories: ["hot_tub"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Use a hot tub plumbing flush product before draining to clean biofilm from the jets and pipes. Clean the shell while empty. Use a hose filter when refilling to reduce minerals. Balance chemistry before first use.",
    whyItMatters: "Over time, dissolved solids build up and make water harder to balance. Biofilm accumulates in plumbing lines. Fresh water every 3-4 months keeps the tub sanitary and extends equipment life.",
  },
  {
    id: "hottub-clean-cover",
    name: "Clean and Condition Hot Tub Cover",
    description: "Wipe down the cover with mild soap, rinse, and apply a UV protectant. Check for waterlogging and damage.",
    category: "pool",
    priority: "prevent_damage",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 20,
    estimatedCostLow: 0,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ["single_family", "townhouse", "multi_family", "mobile_home"],
    applicableSystems: [],
    applicableApplianceCategories: ["hot_tub"],
    seasonalMonths: [],
    healthCategories: [],
    tips: "A waterlogged cover gets extremely heavy and loses insulating ability. If the cover is noticeably heavier than when new, the foam cores are saturated and the cover needs replacement ($300-600). UV protectant extends cover life significantly.",
    whyItMatters: "The cover is the tub's primary insulator — a damaged cover can double heating costs. It also keeps debris and contaminants out of the water.",
  },
  {
    id: "hottub-clean-jets",
    name: "Clean Hot Tub Jets",
    description: "Remove jet inserts if possible and soak in white vinegar. For non-removable jets, run a jet cleaning cycle with a plumbing flush product.",
    category: "pool",
    priority: "efficiency",
    frequencyValue: 3,
    frequencyUnit: "months",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 1500,
    diyDifficulty: "easy",
    applicableHomeTypes: ["single_family", "townhouse", "multi_family", "mobile_home"],
    applicableSystems: [],
    applicableApplianceCategories: ["hot_tub"],
    seasonalMonths: [],
    healthCategories: ["clean_water"],
    tips: "Do this right before a drain-and-refill so the loosened biofilm gets drained away. If jets aren't spinning freely, they may need individual replacement ($10-30 each).",
    whyItMatters: "Biofilm — a slimy bacterial coating — builds up inside jet plumbing and is a major source of water contamination and odors in hot tubs.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// SEASONAL CHECKLISTS
// ═══════════════════════════════════════════════════════════════════════════

const seasonalTemplates: TaskTemplate[] = [
  {
    id: "seasonal-spring-checkup",
    name: "Spring Home Checkup",
    description: "Comprehensive spring walkthrough: inspect roof/gutters after winter, check exterior for damage, service cooling system, start irrigation, clean windows.",
    category: "seasonal",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 120,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [3, 4],
    healthCategories: [],
    tips: "Think of this as a post-winter damage assessment. Walk the entire exterior looking for winter damage: cracked foundations, lifted siding, ice dam damage. Check that downspouts drain away from foundation. Turn on outdoor faucets slowly and check for leaks from frozen pipes. This is a walkthrough — note issues and schedule repairs.",
    whyItMatters: "Winter weather causes more home damage than any other season. Catching problems in spring prevents them from worsening through the year. This is your annual reset.",
  },
  {
    id: "seasonal-summer-checkup",
    name: "Summer Home Checkup",
    description: "Mid-year review: check AC performance, inspect and treat for pests, deep clean kitchen and bathrooms, check irrigation coverage.",
    category: "seasonal",
    priority: "efficiency",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 60,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [6, 7],
    healthCategories: [],
    tips: "Check that your AC keeps up on the hottest days. Walk the yard in early morning looking for dry spots in the lawn (irrigation coverage issues). Check for pest activity — ants, wasps, termite swarmers. Make sure dryer vent flap opens and closes properly.",
    whyItMatters: "Summer heat stresses both your home and its systems. Mid-year checks catch problems before they become emergencies during peak heat.",
  },
  {
    id: "seasonal-fall-winterization",
    name: "Fall Winterization Prep",
    description: "Prepare your home for winter: service heating system, clean gutters, winterize irrigation, insulate pipes, reverse ceiling fans, stock winter supplies.",
    category: "seasonal",
    priority: "prevent_damage",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 120,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [10, 11],
    healthCategories: [],
    tips: "Disconnect and drain garden hoses. Close interior shut-off valves for outdoor faucets and open the outside faucet to drain. Set ceiling fans to clockwise (updraft). Check weather stripping. Stock ice melt, snow shovels, and emergency supplies. Know where your water shut-off is in case of a burst pipe.",
    whyItMatters: "The most expensive home emergencies happen in winter: frozen pipes, heating failures, ice dams. Thirty minutes of fall prep can prevent thousands in winter damage.",
  },
  {
    id: "seasonal-winter-storm-check",
    name: "Winter Storm Readiness Check",
    description: "Verify heating system operation, check emergency supplies, test generator, ensure pipes are protected, review insurance coverage.",
    category: "seasonal",
    priority: "safety",
    frequencyValue: 1,
    frequencyUnit: "years",
    estimatedMinutes: 30,
    estimatedCostLow: 0,
    estimatedCostHigh: 0,
    diyDifficulty: "easy",
    applicableHomeTypes: ALL_HOMES,
    applicableSystems: [],
    applicableApplianceCategories: [],
    seasonalMonths: [12, 1],
    healthCategories: [],
    tips: "Emergency kit: flashlights, batteries, water (1 gallon per person per day for 3 days), non-perishable food, blankets, first aid kit, battery-powered radio, medications. Know how to shut off water, gas, and electricity. If you have a generator, test it and store fresh fuel. Know the signs of ice dams.",
    whyItMatters: "Winter storms can knock out power and heat for days. Being prepared isn't about fear — it's about protecting your family when systems fail. Thousands of families experience this every winter.",
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// COMBINED EXPORT
// ═══════════════════════════════════════════════════════════════════════════

export const TASK_TEMPLATES: TaskTemplate[] = [
  ...hvacTemplates,
  ...plumbingTemplates,
  ...electricalTemplates,
  ...safetyTemplates,
  ...roofGutterTemplates,
  ...exteriorTemplates,
  ...windowDoorTemplates,
  ...applianceTemplates,
  ...lawnTemplates,
  ...pestTemplates,
  ...garageTemplates,
  ...poolTemplates,
  ...hotTubTemplates,
  ...seasonalTemplates,
];
